sahilbooks/models.py
from . import db

# PRODUCT DETAIL TABLE
class Categories(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64), unique=True)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False, default = 'default.jpg')
    book_detail = db.relationship("BookDetail", backref="categories", cascade='all, delete-orphan')

class BookDetail(db.Model):
    __tablename__ = 'book_detail'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False, default = 'default.jpg')
    price = db.Column(db.Float)
    book_id = db.Column(db.Integer, db.ForeignKey('categories.id'))

    def __repr__(self):
        return f"ID: {self.id}\nName: {self.name}\nDescription: {self.description}"

orderdetails = db.Table('orderdetails', 
    db.Column('order_id', db.Integer,db.ForeignKey('orders.id'), nullable=False),
    db.Column('book_id',db.Integer,db.ForeignKey('book_detail.id'),nullable=False),
    db.PrimaryKeyConstraint('order_id', 'book_id') )

# ORDER TABLE
class Order(db.Model):
    __tablename__ = 'orders'
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Boolean, default=False)
    first_name = db.Column(db.String(64))
    surname = db.Column(db.String(64))
    email = db.Column(db.String(128))
    phone = db.Column(db.String(32))
    total_cost = db.Column(db.Float)
    date = db.Column(db.DateTime)
    item_detail = db.relationship("BookDetail", secondary='orderdetails', backref="orders")

sahilbooks/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField
from wtforms.validators import InputRequired, email

# form used in basket
class CheckoutForm(FlaskForm):
    firstname = StringField("Your first name", validators=[InputRequired()])
    surname = StringField("Your surname", validators=[InputRequired()])
    email = StringField("Your email", validators=[InputRequired(), email()])
    phone = StringField("Your phone number", validators=[InputRequired()])
    submit = SubmitField("submit")

sahilbooks/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap4
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

#create a function that creates a web application
# a web server will run this web application
def create_app():
    app = Flask(__name__)
    # Don't leave this enabled in production
    app.debug = True
    
    app.secret_key = 'RevealTheKnowledge100'

    #set the app configuration data 
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///books1.sqlite'

    # initialise db with flask app - necessary because scope of app
    # is only here in create_app, but db is defined globally
    db.init_app(app)
    
    Bootstrap4(app)
    
    #importing modules here to avoid circular references, register blueprints of routes
    from . import views
    app.register_blueprint(views.main_bp)
    #from . import admin
    #app.register_blueprint(admin.admin_bp)
    
    @app.errorhandler(404) 
    # Inbuilt function (to Flask) which takes error as parameter
    def not_found(e): 
      return render_template("error.html", error=e)

    # Handles server errors (look-up 'HTTP response status codes')
    @app.errorhandler(500)
    def internal_error(e):
      return render_template("error.html", error=e)
   
    return app

sahilbooks/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Order, BookDetail, Categories
from datetime import datetime
from .forms import CheckoutForm
from . import db

main_bp = Blueprint('main', __name__)

# Home page
@main_bp.route('/')
def index():
    books = db.session.scalars(db.select(Categories)).all()
    return render_template('index.html', books=books)

# View all the books
@main_bp.route('/bookdetail/<int:book_id>')
def bookdetail(book_id):
   books = db.session.scalars(db.select(BookDetail).where(BookDetail.book_id==book_id)).all()
   return render_template('bookdetails.html', books=books)

# Referred to as "Basket" to the user
@main_bp.route('/order/', methods=['POST', 'GET'])
def order():
    book_id = request.values.get('book_id')
    # retrieve order if there is one
    if 'order_id' in session.keys():
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        # order will be None if order_id/session is stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status=False, first_name='', surname='', email='', phone='', total_cost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('Failed at creating a new order!')
            order = None
    
    # calculate total price
    total_price = 0
    if order is not None:
        for book in order.item_detail:
            total_price += book.price
    
    # are we adding an item?
    if book_id is not None and order is not None:
       book = db.session.scalar(db.select(BookDetail).where(BookDetail.id==book_id))
       if book not in order.item_detail:
           try:
               order.item_detail.append(book)
               db.session.commit()
           except:
               flash('There was an issue adding the item to your basket',category='danger')
           return redirect(url_for('main.order'))
       else:
           flash('There is already one of these in the basket')
           return redirect(url_for('main.order'))
    print(f'Values: {order}')
    return render_template('order.html', order=order.item_detail, total_price=total_price)

# Delete specific basket items
# Note this route cannot accept GET requests now
@main_bp.route('/deleteorderitem/', methods=['POST', 'GET'])
def deleteorderitem():
    id = request.form['id']
    if 'order_id' in session:
        order = db.get_or_404(Order, session['order_id'])
        item_to_delete = db.session.scalar(db.select(BookDetail).where(BookDetail.id==id))
        try:
            order.item_detail.remove(item_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))

# Scrap basket
@main_bp.route('/deleteorder/')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))

# Complete the order
@main_bp.route('/checkout', methods=['POST','GET'])
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = db.get_or_404(Order, session['order_id'])
        if form.validate_on_submit():
            order.status = True
            order.first_name = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            total_cost = 0
            for book in order.item_detail:
                total_cost += book.price
            order.total_cost = total_cost   
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('Thank you! One of our team members will contact you soon...')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form=form)

@main_bp.route('/books')
def search():
    search = request.args.get('search')
    search = '%{}%'.format(search) # substrings will match
    books = BookDetail.query.filter(BookDetail.description.like(search)).all()
    return render_template('search.html', books=books)

sahilbooks/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sahil Books</title>
    <link rel="icon" type="image/png" href="{{url_for('static', filename='img/sahilbooks.png')}}">
    <meta name="description" content="Sahil Books">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <link rel="stylesheet" href="../static/style.css">
    <!-- an example of using css alongside bootstrap -->

</head>

<body>
    <!-- putting header inside container will prevent full width navbar -->

    <header>

        <!--navbar creates a navigation bar -->
        <!-- Colours https://getbootstrap.com/docs/4.6/utilities/colors/ -->

        <nav class="navbar navbar-expand-lg navbar-light bg-book">

            <a class="navbar-brand text-light" href="{{url_for('main.index')}}">
                <img src="{{url_for('static', filename='img/sahilbooks.png')}}" width="30" height="30" class="d-inline-block align-top"
                    alt="Sahil Books Logo">
                Sahil Books
            </a>

            <!-- create a button for collapsing the menu -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">

                <!-- individual menu item-->
                <a class="nav-item nav-link active" href="about.html">About Us</a>

                <!-- individual menu item-->
                <a class="nav-item nav-link" href="{{url_for('main.index', _anchor='books_anchor')}}">Books</a>

                <!-- individual menu item-->
                <a class="nav-item nav-link" href="{{url_for('main.order')}}">Basket</a>

                <!-- test of 404 page-->
                <a class="nav-item nav-link" href="clients.html">Our Clients</a>

                <!-- right aligned menu items thanks to ml-auto -->
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                        <!-- text like phone number -->
                        <span class="navbar-contact nav-item nav-link"><a href="tel: +61420562762">+61420562762</a></span>
                    </li>
                    <li class="nav-item">
                        <!-- search box -->
                        <form class="form-inline my-2 my-lg-0 ml-5" action="{{url_for('main.search')}}">
                            <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="search">
                            <button class="search-btn btn-outline-black btn btn-secondary btn-s my-0 ml-1" type="submit">Search</button>
                        </form>
                    </li>
                </ul>

        </nav>

        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-primary m-2" role="alert">
            {% for message in messages %}
                {{message}}
            {% endfor %}
            </div>
        {% endif %}
        {% endwith %} 

        {% block head %}
        
        {% endblock %}

    </header>


    <!-- main page content goes in container -->
    <div class="container-fluid">
        <main>
            {% block main %}
            
            {% endblock %}
        </main>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container text-center">
            <p>Copyright &copy; Sahil Books</p>
        </div>
    </footer>
    <!-- Footer -->


    <!-- jQuery first, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

</body>

</html>

sahilbooks/templates/bookdetails.html
{% extends 'base.html' %}

{% block main %}

<section>

    <div class="text-dark text-center">
        <div>
            <p class="h3 text-dark mb-4">Select a book from below</p>
        </div>
    </div>

    <div class="card-columns">
        <!-- each tour is a bootstrap card -->
        <div class="row">
            
            {% for book in books%}
            <div class=" col-lg-6">
                <div class="card">
                    <img class="card-img-top" src="{{url_for('static', filename='img/'+book.image)}}" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title">{{book.name}}</h4>
                        <p class="card-text">{{book.description}}</p>
                    </div>
                
                    <div class="card-footer">
                        <form action="{{url_for('main.order')}}">
                            <input type="hidden" id="book_id" name="book_id" value="{{book.id}}">
                            <input class="btn book-btn" type="submit" value="Add to Basket">
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
        
    </div>

</section>
{% endblock %}

sahilbooks/templates/checkout.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_form %}

{% block main %}
    <section>  
        <div class="container">
            <div class="row">
                <div class = "col-12">
                    <h1>Checkout</h1>
                    <p>
                        Thank you for your interest. Please provide your details so that one of our awesome tour agents can contact you to finalize details and take payment. Thank you! 
                    </p>
                </div>
            </div>
            <div class="row">
                <div class = "col-6">
                    {{render_form(form)}}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

sahilbooks/templates/error.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
    <h1>Error</h1>
    <p>Sorry, but something went wrong!</p>
    <p>More info: {{error}}</p>
</div>
{% endblock %}

sahilbooks/templates/index.html
{% extends 'base.html' %}

{% block head %}
<div class="jumbotron jumbotron-fluid card card-image" style="background-image: url('../static/img/BOOKSHELVES.jpeg');">
    <div class="text-white text-center py-5 px-4">
        <div>
            <h1 class="display-2">Welcome to Sahil Books</h1>
            <p class="display-4 text-info">Start your knowledge journey from here</p>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}
<section class="container-fluid bg-book">
    <div class="container">
        <div class="text-white text-center">
            <div>
                <p class="h1 text-info mb-4">Why us<span class="text-secondary">?</span></p>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-4">
                <article>
                    <h2 class="text-white">Wide range of varieties</h2>
                    <p>Want to fly in the fantasy of fairytales or make growth of knowledge?<br>get everything at one place </p>
                    <ul>
                        <li>Fantasy</li>
                        <li>Finance</li>
                    </ul>
                </article>

            </div>


            <div class="col-md-4">
                <article>
                    <h2 class="text-white">Easy exchange offer</h2>
                    <p class="text-olive">Are you avid reader but that started affecting your pocket</p>
                    <p>Forget about budget, with motto of spreading knowledge we provide you great discount on exchange of your old books</p>
                    <p class="text-navy">visit physically at store to sel you book</p>
                </article>
            </div>

            <div class="col-md-4">
                <article>
                    <h2 class="text-white">Affordable selections</h2>
                    <p>We have <span> great prices and offers </span> all year round!</p>
                    <p>Click <a href="discounts.html" class="discount">here</a> for more information.</p>
                </article>
            </div>
        </div>
        <!-- Horizontal Rule -->
        <hr>
    </div>
</section>

<!-- display the books to the user -->
<section class="bg-book-light py-5">
    <div class="text-dark text-center">
        <div>
            <p class="h3 text-white mb-4" id="books_anchor">Pick a book</p>
        </div>
    </div>
    <div class="card-deck">
        <div class=" col-lg-3"></div>
        {% for book in books %}
        <div class="card col-lg-3 col-sm-12 py-2">
            <img class="card-img-top" src="../static/img/{{book.image}}" alt="Card image">
            <div class="card-body">
                <h4 class="card-title">{{book.title}}</h4>
                <p class="card-text">{{book.description}}</p>
            </div>
            <div class="card-footer"><a href= "{{url_for('main.bookdetail', book_id=book.id)}}" class="btn book-btn">Book Detail</a></div>
        </div>
        {% endfor %}
        <div class="col-lg-3"></div>
    </div>
</section>
{% endblock %}

sahilbooks/templates/order.html
{% extends 'base.html' %}

{% block main %}
<!-- display contents of user basket -->
<section>  
    <div class="container">
        <div class="row co-12 d-flex mt-2 mb-2">
            <h3>Shopping Basket</h3>
        </div>

        <!-- each tour on seperate row -->
        {% for book in order %}
            <div class="row shadow-md my-row mb-3">
                <div class="col-sm-10 card">
                    <h5 class="card-header">{{book.name}}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                <img class="img-thumbnail" src="{{url_for('static', filename=('img/' + book.image))}}">
                            </div>
                            <div class="col-10">
                                <!-- Item Description -->
                                <p class="card-text">{{book.description}}</p>   
                            </div>  
                        </div>                      
                    </div>
                </div>
                <br><br>
                <!-- right column has price and delete button -->
                <div class="col-sm-2">
                <!-- delete item button -->
                    <h5 class="mt-2">{{"$%.2f"|format(book.price)}}</h5>
                    <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                        <input type="hidden" id="id" name="id" value="{{book.id}}">
                        <input type="submit" value="Delete" class="btn book-btn mb-3">
                    </form> 
                </div>
            </div>
        {% endfor %}
        
        <!-- total price and page controls -->
        <section>
            <div class="row co-12 d-flex">
                <h5 class="mt-4">Quote = {{"$%.2f"|format(total_price)}}</h5>
            </div>
            <div class="row co-12 d-flex mt-2 mb-4">
                <a href="{{url_for('main.index', _anchor='cities_anchor')}}" class="btn book-btn mr-4">Books</a>
                <a href="{{url_for('main.checkout')}}" class="btn book-btn mr-4">Checkout</a>
                <a href="{{url_for('main.deleteorder')}}" class="btn book-btn">Empty Basket</a>
            </div>
        </section>
    </div>
</section>

{% endblock %}

sahilbooks/templates/search.html
{% extends 'base.html' %}

{% block main %}
<!-- display contents of user basket -->
<section>  
    <div class="container">

        <!-- each tour on seperate row -->
        {% for book in books %}
        <div class="row">
x
            <div class="row shadow-md my-row mb-3">
                <div class="col-10 card">
                    <h5 class="card-header">{{book.name}}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                <img class="img-thumbnail" src="{{url_for('static', filename=('img/' + book.image))}}">
                            </div>
                            <div class="col-10">
                                <!-- Item Description -->
                                <p class="card-text">{{book.description}}</p>   
                            </div>  
                        </div>                      
                    </div>
                </div>

                <div class="col-2">
                    <div class="card-footer">
                        <form action="{{url_for('main.order')}}">
                            <input type="hidden" id="book_id" name="book_id" value="{{book.id}}">
                            <input class="btn book-btn" type="submit" value="Add to Basket">
                        </form>
                    </div> 
                </div>
                
                
                
            </div>
            
        </div>
            {% endfor %}
        </div>
</section>

{% endblock %}